### ISSUE TITLE
Print error string in logs when messages aren't flushed successfully.

### ISSUE THREAD

**Issue by mdobson** [apigee/microgateway-plugins#25]

**Comment by gbrail** [comment]
FWIW, I tested this with the early access and apid. I get errors relating to analytics push when I try to make API calls in parallel (I like to use "apib" for my testing but there are lots of tools). When I make one API call at a time it works fine. I couldn't easily reproduce this with apid on its own.

**Comment by mdobson** [comment]
I see. I'll introduce apib into my testing regimen.

**Comment by mdobson** [comment]
https://github.com/apigee/microgateway-plugins/pull/28
