### ISSUE TITLE
Ability to skip oauth plugin

### ISSUE THREAD

**Issue by philschleier** [apigee/microgateway-plugins#53]
Hi, we have a requirement to expose certain endpoints without apikey/oauth validation.
The validation of whether or not to skip a certain URL is not the issue, we can do that in a separate plugin. The question is how can we tell the oauth plugin to skip execution?

I propose introducing an attribute on the request (req.skip, for example) and adding a simple check `if (req.skip) next()` to the oauth plugin. 
1) is there another way to achieve this that I'm not seeing?
2) can we get this into the oauth plugin as I can't just fork & rename the oauth plugin (because the injected plugin configuration is dependent on the plugin name)

Regards,
Philipp

**Comment by srinandan** [comment]
@philschleier , you might want to consider v2.6.1-alpha. This allows you to set plugins for each proxy.

Another option is to have two MG instances on the same machine. One which only exposes proxies that need OAuth another another that doesn't.
