### ISSUE TITLE
OAuth issue : err is not defined in console.warn

### ISSUE THREAD

**Issue by celcius112** [apigee/microgateway-plugins#74]
In the function `verify` in the `index.js` file of the OAuth package, the variable `err` is not defined and as such throws an unhandled exception in the `console.warn()`, for example on [line 250](https://github.com/apigee/microgateway-plugins/blob/master/oauth/index.js#L250).

**Comment by srinandan** [comment]
Yep, that's a bug. Will fix it

**Comment by srinandan** [comment]
Fixed in microgateway-plugin: 2.3.22
