### ISSUE TITLE
Quota plugin request logic on EDGEMICRO_LOCAL seems reversed

### ISSUE THREAD

**Issue by heckler** [apigee/microgateway-plugins#86]
Looking at the quota plugin, the check for local mode appears reversed:

https://github.com/apigee/microgateway-plugins/blob/master/quota/index.js#L61-L65

For the 'if' test clause to match the debug message it should be reversed: `!process.env.EDGEMICRO_LOCAL` or `process.env.EDGEMICRO_LOCAL != "1"`

**Comment by dschniepp** [comment]
This issue should be closed or am I wrong?

**Comment by srinandan** [comment]
yes, this should be closed.
